[package]
org = "windhoek"
name = "admin-service"
version = "1.0.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[dependencies]
ballerina/http = "2.10.0"
ballerina/sql = "1.7.0"
ballerina/mysql = "1.7.0"
ballerina/log = "2.7.0"
ballerina/io = "1.5.0"
ballerina/time = "2.3.0"
ballerina/uuid = "1.5.0"
ballerina/jwt = "2.4.0"
ballerina/constraint = "1.1.0"
ballerina/regex = "1.4.0"
ballerina/kafka = "4.0.0"
